/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "noTranslations": true,
  "name": "Square block text inputs",
  "description": "Makes text and color inputs on blocks rectangular instead of round, like in Scratch 2.0.",
  "credits": [
    {
      "name": "CST1229",
      "link": "https://scratch.mit.edu/users/CST1229/"
    }
  ],
  "tags": [
    "theme",
    "new"
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "settings": [
    {
      "dynamic": true,
      "name": "Text inputs",
      "id": "text",
      "type": "boolean",
      "default": true
    },
    {
      "dynamic": true,
      "name": "Color inputs",
      "id": "color",
      "type": "boolean",
      "default": true
    }
  ],
  "dynamicDisable": true
};
export default manifest;
