/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "noTranslations": true,
  "name": "Rearrangeable custom block inputs",
  "description": "Adds buttons for rearranging custom block inputs.",
  "credits": [
    {
      "name": "Chrome_Cat",
      "link": "https://scratch.mit.edu/users/Chrome_Cat/"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "arrows.css"
    }
  ],
  "tags": [
    "recommended",
    "new"
  ],
  "enabledByDefault": true,
  "dynamicDisable": true
};
export default manifest;
